# Generated by Django 3.2 on 2024-08-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=100)),
                ('warehouse_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_parts/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='car_parts/thumbnails/')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.carpart')),
            ],
        ),
    ]
