# Generated by Django 4.2.15 on 2024-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_carpartimage_options_carpartimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpartimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_parts/'),
        ),
    ]
